import test from "node:test";
import assert from "node:assert/strict";
import type { CompanionInput } from "../../studio/companion.ts";
import type { Json } from "../../core/value.ts";
import { emptyProjection } from "../../studio/projection.ts";
import { VISUAL_IR_VERSION } from "../../render/ir.ts";
import { assembleStickerProgram } from "../../components/comment-sticker/program.ts";
import { resolveProperties } from "../../components/comment-sticker/shared.ts";
import { stickerRules } from "../../components/comment-sticker/validate.ts";
import { stickerTypes } from "../../components/comment-sticker/types.ts";
import { projectWindow } from "../../timeline/temporal.ts";
import module from "./index.ts";
const timeline = { axisKey: "axis", clock: { fps: { numerator: 30, denominator: 1 } }, totalFrames: 90, placements: [] };
const canvas = { canvasKey: "canvas", extent: { widthPx: 720, heightPx: 1280 } };
test("sticker authored copy is a distinct body layer, never a review comment, and avatar decoration owns only its nodes", () => {
  const style = { styleKey: "style", properties: resolveProperties({}, stickerRules), fonts: { stackKey: "fonts", faces: [{ faceKey: "face", family: "inter", weight: 700, style: "normal" as const, shards: [{ resource: { $resource: "font", bytes: 100, mime: "font/woff2" }, unicodeRange: "U+0-10FFFF" }], license: { spdx: "OFL-1.1", notice: { $resource: "license", bytes: 100, mime: "text/plain" } } }] } };
  const program = assembleStickerProgram("track", timeline, canvas, [{ itemKey: "sticker", comment: "Authored body\nSecond line", author: "@alex", header: "A reply", meta: "Today", avatar: { $resource: "avatar", bytes: 100, mime: "image/png" } }], [{ canvasKey: "canvas", rect: { xPx: 40, yPx: 500, widthPx: 640, heightPx: 280 } }], [projectWindow(timeline, { kind: "edges", start: "10f", end: "70f" }, "sticker")], [style]);
  const value = { type: stickerTypes.program, data: program as unknown as Json };
  const input: CompanionInput = { value, type: value.type, moduleId: module.id, surface: "Track", output: "program", outputKey: "track.program", authorKey: "author", authorGraph: { source: "source", sources: [], records: new Map(), operations: new Map(), outputs: new Map(), publicRecords: new Map(), assets: new Map(), modules: [] }, authoring: { units: new Map(), elements: new Map(), relations: [], inputs: [], references: [] }, inputs: {}, executionEdges: [], supports: {}, timeline, document: { version: VISUAL_IR_VERSION, compositionKey: "composition", domain: { ...timeline, totalSamples48k: 144000 }, extent: canvas.extent, resources: [], surfaces: [], html: "" }, provenance: { kind: "author" }, fallback: emptyProjection };
  const result = module.studio![0]!.project(input);
  const body = result.entities.find(entity => entity.text)!;
  const avatar = result.entities.find(entity => entity.facts.role === "decoration")!;
  assert.equal(body.text, "Authored body\nSecond line");
  assert.equal(body.facts.kind, "author-content");
  assert.deepEqual(body.intervals, [{ start: 10, end: 70 }]);
  assert.ok(body.pictureParts.includes("sticker/body"));
  assert.deepEqual(avatar.pictureParts, ["sticker/avatar"]);
  assert.equal(body.pictureParts.some(part => avatar.pictureParts.includes(part)), false);
  assert.equal(result.materials[0]!.resource?.$resource, "avatar");
  const copy = result.fieldGroups.find(group => group.sectionKey === "Copy")!;
  assert.deepEqual(copy.fields.map(field => field.authorValue), ["Authored body\nSecond line", "@alex", "A reply", "Today"]);
  assert.deepEqual(result.fieldGroups.filter(group => group.domain === "When").map(group => group.sectionKey), ["Motion"]);
});
