import test from "node:test";
import assert from "node:assert/strict";
import type { CompanionInput } from "../../studio/companion.ts";
import type { Json } from "../../core/value.ts";
import { emptyProjection } from "../../studio/projection.ts";
import { VISUAL_IR_VERSION } from "../../render/ir.ts";
import { assembleEmojiProgram } from "../../components/interview-emoji-reveal/program.ts";
import { resolveProperties } from "../../components/comment-sticker/shared.ts";
import { emojiRules } from "../../components/interview-emoji-reveal/validate.ts";
import { emojiTypes, type EmojiPlan } from "../../components/interview-emoji-reveal/types.ts";
import { projectWindow } from "../../timeline/temporal.ts";
import module from "./index.ts";
const timeline = { axisKey: "axis", clock: { fps: { numerator: 30, denominator: 1 } }, totalFrames: 60, placements: [] };
const canvas = { canvasKey: "canvas", extent: { widthPx: 720, heightPx: 1280 } };
const image = { $resource: "icon", bytes: 100, mime: "image/png" };
test("reveal event is an exact instant, not the permanent answer or placeholder visibility window", () => {
  const plan: EmojiPlan = { trackKey: "track", items: [{ itemKey: "preset", preset: true }, { itemKey: "reveal", preset: false, at: { kind: "at", source: "20f" } }] };
  const program = assembleEmojiProgram(timeline, canvas, { styleKey: "style", properties: resolveProperties({}, emojiRules) }, projectWindow(timeline, { kind: "edges", start: "10f", end: "50f" }, "track"), image, plan, [image, image]);
  const value = { type: emojiTypes.program, data: program as unknown as Json };
  const input: CompanionInput = { value, type: value.type, moduleId: module.id, surface: "Track", output: "program", outputKey: "track.program", authorKey: "author", authorGraph: { source: "source", sources: [], records: new Map(), operations: new Map(), outputs: new Map(), publicRecords: new Map(), assets: new Map(), modules: [] }, authoring: { units: new Map(), elements: new Map(), relations: [], inputs: [], references: [] }, inputs: { plan: [{ type: emojiTypes.plan, data: plan as unknown as Json }] }, executionEdges: [], supports: {}, timeline, document: { version: VISUAL_IR_VERSION, compositionKey: "composition", domain: { ...timeline, totalSamples48k: 96000 }, extent: canvas.extent, resources: [], surfaces: [], html: "" }, provenance: { kind: "author" }, fallback: emptyProjection };
  const result = module.studio![0]!.project(input);
  const trigger = result.entities.find(entity => entity.facts.kind === "instant")!;
  const answer = result.entities.find(entity => entity.title === "Answer 2")!;
  const placeholder = result.entities.find(entity => entity.selectionGroup === answer.editorKey && entity.facts.role === "decoration")!;
  assert.deepEqual(trigger.intervals, [{ start: 20, end: 21 }]);
  assert.deepEqual(answer.visibleIntervals, [{ start: 20, end: 50 }]);
  assert.deepEqual(placeholder.visibleIntervals, [{ start: 10, end: 20 }]);
  assert.deepEqual(trigger.temporal, []);
  assert.deepEqual(answer.temporal, []);
  assert.deepEqual(trigger.pictureParts, []);
  assert.ok(answer.pictureParts.includes("reveal/answer"));
  assert.deepEqual(placeholder.pictureParts, ["reveal/placeholder"]);
  assert.equal(answer.pictureParts.some(part => placeholder.pictureParts.includes(part)), false);
  assert.equal(result.entities[0]!.pictureParts.some(part => answer.pictureParts.includes(part)), false);
  assert.deepEqual(result.lanes.map(lane => lane.height), [52, 40]);
});
