import type { Json, ResourceRef } from "../../core/value.ts";
import type { Timeline, Clock, Bounds, InstantExpression, Window } from "../../timeline/types.ts";
import type { Frame, Canvas, Extent, Path } from "../../space/types.ts";
import type { Surface, Easing } from "../../render/ir.ts";
import type { PerformanceStyle } from "../types.ts";
import type { SynchronizedMedia } from "../../timeline/types.ts";
export const mediaTrackTypes = { plan: "dsivio-video/media-track@1#Plan", program: "dsivio-video/media-track@1#Program" } as const;
export type MediaPlayback = "once-start" | "once-end" | "hold-start" | "hold-end" | "loop-start" | "loop-end" | "stretch";
export type MediaAppearance = PerformanceStyle & { playback: MediaPlayback; trim?: Bounds };
export type MediaSource = { kind: "image"; resource: ResourceRef; extent: Extent } | { kind: "media"; media: SynchronizedMedia } | { kind: "surface"; surface: Surface };
export type MotionEffect = "none" | "fade" | "slide" | "scale" | "pop" | "bounce" | "blur-reveal" | "wipe" | "flip" | "spin";
export type Direction = "left" | "right" | "up" | "down";
export type MotionEdge = { effect: MotionEffect; frames: number; easing: Easing; direction?: Direction; amount?: number; outsideCanvas?: boolean };
export type MediaMotion = { enter: MotionEdge; exit: MotionEdge; sustain: { effect: "float" | "breathe" | "pulse" | "wobble" | "shake" | "drift"; amount: number; cycles: number; direction?: Direction }[] };
export type Sampling = { at: number; zoom: number; x: number; y: number; rotate: number; easing?: Easing };
export type LayerPlan = { id: string; kind: "image" | "media" | "surface" | "paint"; sourceIndex: number; extentIndex?: number; properties: Record<string, Json>; sampling: Sampling[] };
export type UnitPlan = { id: string; layers: LayerPlan[]; properties?: Record<string, Json>; sourceAudio?: string; audioGain: number; instant?: InstantExpression };
export type HandoffPlan = { id: string; from: string; operator: "cut" | "crossfade" | "push" | "wipe" | "cover" | "page-turn"; duration: number; ratio: number; direction?: Direction; audio: "cut" | "crossfade" };
export type SoundPlan = { id: string; sourceIndex: number; gain: number; at?: "enter" | "exit"; handoff?: string };
export type GroupPlan = { id: string; frameIndex: number; properties: Record<string, Json>; motion: MediaMotion; clipIndex?: number; windowIndex?: number; until?: InstantExpression; units: UnitPlan[]; handoffs: HandoffPlan[]; sounds: SoundPlan[] };
export type MediaPlan = { trackKey: string; groups: GroupPlan[]; hasAudio: boolean };
export type ResolvedLayer = { plan: LayerPlan; source?: MediaSource; appearance?: MediaAppearance };
export type ResolvedUnit = { plan: UnitPlan; logical: Bounds; visual: Bounds; layers: ResolvedLayer[] };
export type MediaGroup = { plan: GroupPlan; frame: Frame; appearance: MediaAppearance; lifetime: Bounds; units: ResolvedUnit[]; handoffs: { plan: HandoffPlan; boundary: number; frames: Bounds }[]; sounds: { plan: SoundPlan; source: SynchronizedMedia; frame: number }[]; clip?: Path };
export type MediaProgram = { trackKey: string; timeline: Timeline; canvas: Canvas; groups: MediaGroup[]; hasAudio: boolean };
export type MediaInputs = { frames: Frame[]; images: ResourceRef[]; media: SynchronizedMedia[]; surfaces: Surface[]; extents: Extent[]; clips: Path[]; windows: Window[] };
export type SourceTiming = { clock: Clock; totalFrames: number };
