import type { Binding, ModuleDef } from "../../core/module.ts";
import type { Json, Value } from "../../core/value.ts";
import { entityIdentity } from "../../timeline/identity.ts";
import { attributes, literal, reference, empty, parseNumber } from "../../space/parse.ts";
import { validateFaceRequest } from "../../fonts/catalog.ts";
import { validateFontFace, validateFontStack } from "../../fonts/validate.ts";
import { fontTypes } from "../../fonts/types.ts";
import type { FontFace, FontStack } from "../../fonts/types.ts";
import { DvError } from "../../core/errors.ts";
const id="dsivio-video/fonts@1"; const requestType=`${id}#FaceRequest`;const keyType=`${id}#StackKey`;
const fonts:ModuleDef={id,summary:"Pinned exact WOFF2 fonts; ordered explicit fallback and emoji.",types:{Face:{summary:"Exact face with licences",validate:validateFontFace},Stack:{summary:"Ordered duplicate-free exact faces",validate:validateFontStack},FaceRequest:{summary:"Private exact face request",validate:validateFaceRequest},StackKey:{summary:"Private stack identity",validate(d){if(typeof d!=="string"||!d.trim())throw new DvError("TYPE_INVALID","Stack identity is required");}}},
 surfaces:{
 Face:{mode:"structured",doc:{summary:"Read an explicitly prepared pinned exact face.",attributes:["id","family","weight","style"].map(name=>({name,required:true,accepts:"text",summary:name})),outputs:[{name:"",type:fontTypes.face,summary:"Exact face"}]},elaborate(e,ctx){const a=attributes(e,["id","family","weight","style"],ctx);empty(e,ctx);const name=literal(a.id,"id",ctx,e);const request={faceKey:entityIdentity(ctx.file,name),family:literal(a.family,"family",ctx,e),weight:parseNumber(literal(a.weight,"weight",ctx,e)),style:literal(a.style,"style",ctx,e)};validateFaceRequest(request);ctx.operation({producer:`${id}#face`,inputs:{request:ctx.record(null,{type:requestType,data:request},e.span)},publish:{face:name},label:name,span:e.span});}},
 Stack:{mode:"structured",doc:{summary:"Explicit primary, fallbacks and optional pinned emoji.",attributes:[{name:"id",required:true,accepts:"text",summary:"Identity"},{name:"font",required:true,accepts:fontTypes.face,summary:"Primary face"},{name:"emoji",required:false,accepts:"one of color|mono",summary:"Append emoji"}],children:[{tag:"Fallback",repeat:true,summary:"Exact fallback face"}],outputs:[{name:"",type:fontTypes.stack,summary:"Ordered stack"}]},elaborate(e,ctx){const a=attributes(e,["id","font","emoji"],ctx);const name=literal(a.id,"id",ctx,e);const faces:Binding[]=[reference(a.font,[fontTypes.face],ctx,e)];if(e.kind!=="element")return ctx.fail("MARKUP_CHILD","Stack must be structured",e.span);for(const c of e.children){if(c.kind==="text"&&!c.text.trim())continue;if(c.kind!=="element"||c.tag.split(":").at(-1)!=="Fallback")return ctx.fail("MARKUP_CHILD","Stack only accepts Fallback",c.span);const ca=attributes(c,["font"],ctx);empty(c,ctx);faces.push(reference(ca.font,[fontTypes.face],ctx,c));}if(a.emoji){const emoji=literal(a.emoji,"emoji",ctx,e);if(emoji!=="mono"&&emoji!=="color")return ctx.fail("FONT_UNSUPPORTED","emoji must be color or mono",a.emoji.span);const request={faceKey:entityIdentity(ctx.file,`${name}/emoji`),family:emoji==="mono"?"noto-emoji":"noto-color-emoji",weight:400,style:"normal"};faces.push(ctx.operation({producer:`${id}#face`,inputs:{request:ctx.record(null,{type:requestType,data:request},e.span)},publish:{},label:`${name}/emoji`,span:e.span}).face!);}ctx.operation({producer:`${id}#stack`,inputs:{faces,key:ctx.record(null,{type:keyType,data:entityIdentity(ctx.file,name)},e.span)},publish:{stack:name},label:name,span:e.span});}}
 },
 producers:{face:{inputs:{request:{type:requestType}},outputs:{face:fontTypes.face},run(inputs){return{needs:{face:{capability:"local/font-face",request:(inputs.request as Value).data}}};}},stack:{inputs:{faces:{type:fontTypes.face,list:true},key:{type:keyType}},outputs:{stack:fontTypes.stack},run(inputs){const stack:FontStack={stackKey:(inputs.key as Value).data as string,faces:(inputs.faces as Value[]).map(v=>v.data as unknown as FontFace)};validateFontStack(stack);return{outputs:{stack:{type:fontTypes.stack,data:stack as unknown as Json}}};}}}
};
export default fonts;
