import { DvError } from "../../core/errors.ts";
import type { Json } from "../../core/value.ts";
import type { ElaborationContext } from "../../core/module.ts";
import type { Attribute, ElementNode, RawElement } from "../../markup/ast.ts";
import type { FontFace, FontStack } from "../../fonts/types.ts";
import type { TypographyStyle, TypographyMotion } from "../types.ts";
import type { Paint, Ink, Decoration, AnimatedProperty, Easing } from "../../render/ir.ts";
import type { Recipe } from "../../modules/recipe/index.ts";
import { attributes, literal, empty, parseNumber } from "../../space/parse.ts";
import { validateTextFormat, validateTextFlow, validatePaint, validateTextOpenType, validateTextDecorations } from "../../render/text-runtime.ts";
export type TypographyStyleExtras = {paints:Paint[];axes:{tag:string;value:number}[];features:{tag:string;enabled:boolean}[];decorations:Decoration[]};
export function validateStyleExtras(value:unknown):asserts value is TypographyStyleExtras {
 if(value===null||typeof value!=="object"||Array.isArray(value))throw new DvError("TYPE_INVALID","Style extras must be an object");
 const d=value as Record<string,unknown>;
 if(Object.keys(d).some(key=>!["paints","axes","features","decorations"].includes(key))||!Array.isArray(d.paints))throw new DvError("TYPE_INVALID","Invalid style extras");
 d.paints.forEach(validatePaint);validateTextOpenType(d.axes,d.features);validateTextDecorations(d.decorations);
}
export const recipeKeys=["stack-order","size","weight","font-style","line-height","tracking","word-spacing","kerning","synthesis","language","direction","writing-mode","baseline-shift","vertical-align","tab-size","indent","paragraph-before","paragraph-after","transform","caps","cjk-spacing","punctuation-trim","fill","inline-size","block-size","padding","align","block-align","wrap","overflow","max-lines","minimum-scale","clip","columns","column-gap","metric-edge","point-anchor-inline","point-anchor-block","path-side","path-orientation","path-start-margin","path-end-margin","path-align","path-reverse","path-overflow"];
export function sides(value:unknown):[number,number,number,number] {
 const values=typeof value==="number"?[value]:typeof value==="string"?value.trim().split(/\s+/).map(parseNumber):[];
 if(![1,2,4].includes(values.length)||values.some(v=>!Number.isFinite(v)||v<0))throw new DvError("TYPO_RECIPE","Sides require 1, 2 or 4 nonnegative numbers");
 return values.length===1?[values[0]!,values[0]!,values[0]!,values[0]!]:values.length===2?[values[0]!,values[1]!,values[0]!,values[1]!]:values as [number,number,number,number];
}
export function typographyStyle(styleKey:string,recipe:Recipe,font:FontFace|FontStack,extra:{paints:Paint[];axes:{tag:string;value:number}[];features:{tag:string;enabled:boolean}[];decorations:Decoration[]}):TypographyStyle {
 const p=recipe.properties;for(const n of Object.keys(p))if(!recipeKeys.includes(n))throw new DvError("TYPO_RECIPE",`Unknown typography recipe property ${n}`);
 const n=(name:string,fallback?:number):number=>{const v=p[name]??fallback;if(typeof v!=="number"||!Number.isFinite(v))throw new DvError("TYPO_RECIPE",`${name} requires a finite number`);return v;};
 const t=(name:string,fallback:string):string=>{const v=p[name]??fallback;if(typeof v!=="string")throw new DvError("TYPO_RECIPE",`${name} requires text`);return v;};
 const b=(name:string):boolean=>{const v=p[name]??false;if(typeof v!=="boolean")throw new DvError("TYPO_RECIPE",`${name} requires boolean`);return v;};
 const fonts:FontStack="faces"in font?font:{stackKey:styleKey+"/font",faces:[font]};const primary=fonts.faces[0]!;
 if(p.weight!==undefined&&p.weight!==primary.weight||p["font-style"]!==undefined&&p["font-style"]!==primary.style)throw new DvError("TYPO_FONT_CONFLICT","Typography weight and style must match the exact primary Face");
 const paints:Paint[]=[];if(p.fill!==undefined)paints.push({kind:"fill",ink:{kind:"solid",color:t("fill","")}});paints.push(...extra.paints);
 const format={fonts,sizePx:n("size"),lineHeight:n("line-height",1.2),trackingPx:n("tracking",0),wordSpacingPx:n("word-spacing",0),axes:extra.axes,features:extra.features,...(p.language!==undefined?{language:t("language","")} :{}),direction:t("direction","auto"),writingMode:t("writing-mode","horizontal-tb"),kerning:t("kerning","auto"),synthesis:t("synthesis","none"),baselineShiftPx:n("baseline-shift",0),verticalAlign:t("vertical-align","baseline"),tabSize:n("tab-size",4),indentPx:n("indent",0),paragraphBeforePx:n("paragraph-before",0),paragraphAfterPx:n("paragraph-after",0),transform:t("transform","none"),caps:t("caps","normal"),cjkSpacing:t("cjk-spacing","normal"),punctuationTrim:t("punctuation-trim","none"),paints,decorations:extra.decorations};validateTextFormat(format);
 const layout={mode:"area",inlineSize:t("inline-size","fixed"),blockSize:t("block-size","fixed"),align:t("align","center"),blockAlign:t("block-align","center"),paddingPx:sides(p.padding??0),wrap:t("wrap","word"),overflow:t("overflow","visible"),columns:n("columns",1),columnGapPx:n("column-gap",0),...(p["max-lines"]!==undefined?{maxLines:n("max-lines")}:{}),...(p["minimum-scale"]!==undefined?{minimumScale:n("minimum-scale")}:{}),metricEdge:t("metric-edge","line-box"),pointAnchor:{inline:t("point-anchor-inline","center"),block:t("point-anchor-block","center")},clip:b("clip")};
 const probe={format,layout,paragraphs:[{paragraphKey:"probe",runs:[{kind:"run",runKey:"probe/run",text:"x"}]}],sequences:[]};validateTextFlow(probe);
 const layer=n("stack-order");if(!Number.isSafeInteger(layer))throw new DvError("TYPO_RECIPE","stack-order must be a safe integer");
 const path={side:t("path-side","left"),orientation:t("path-orientation","follow"),startMarginPx:n("path-start-margin",0),endMarginPx:n("path-end-margin",0),reverse:b("path-reverse"),align:t("path-align","start"),overflow:t("path-overflow","visible")};
 if(!["left","right"].includes(path.side)||!["follow","upright"].includes(path.orientation)||!["start","center","end"].includes(path.align)||!["visible","clip"].includes(path.overflow)||path.startMarginPx<0||path.endMarginPx<0)throw new DvError("TYPO_RECIPE","Invalid text path style");
 return {styleKey,layer,format:probe.format,layout:probe.layout,outerStyle:[],path:path as TypographyStyle["path"]};
}
function children(e:ElementNode|RawElement,ctx:ElaborationContext):ElementNode[]{if(e.kind!=="element")return ctx.fail("MARKUP_CHILD","Expected structured typography",e.span);const result:ElementNode[]=[];for(const c of e.children){if(c.kind==="text"&&!c.text.trim())continue;if(c.kind!=="element")return ctx.fail("MARKUP_CHILD","Only declared elements are allowed",c.span);result.push(c);}return result;}
export function decodeStyleChildren(e:ElementNode|RawElement,ctx:ElaborationContext):TypographyStyleExtras {
 const result:TypographyStyleExtras={paints:[],axes:[],features:[],decorations:[]};
 const tag=(e:ElementNode)=>e.tag.split(":").at(-1)!;
 function decodeInk(e:ElementNode,a:Record<string,Attribute>):Ink {const gradients=children(e,ctx).filter(c=>["Linear","Radial"].includes(tag(c)));if((a.color?1:0)+gradients.length!==1)return ctx.fail("TYPO_PAINT","Paint requires one color or gradient",e.span);if(a.color)return{kind:"solid",color:literal(a.color,"color",ctx,e)};const g=gradients[0]!;const linear=tag(g)==="Linear";const ga=attributes(g,linear?["angle"]:["x","y"],ctx);const stops=children(g,ctx).map(s=>{if(tag(s)!=="Stop")return ctx.fail("MARKUP_CHILD","Gradient only accepts Stop",s.span);const sa=attributes(s,["offset","color","opacity"],ctx);empty(s,ctx);return{offset:parseNumber(literal(sa.offset,"offset",ctx,s)),color:literal(sa.color,"color",ctx,s),opacity:parseNumber(literal(sa.opacity,"opacity",ctx,s,"1"))};});return linear?{kind:"linear",angleDegrees:parseNumber(literal(ga.angle,"angle",ctx,g)),stops}:{kind:"radial",centerX:parseNumber(literal(ga.x,"x",ctx,g)),centerY:parseNumber(literal(ga.y,"y",ctx,g)),stops};}
 for(const c of children(e,ctx)){const name=tag(c);if(name==="Axis"||name==="Feature"){const a=attributes(c,name==="Axis"?["tag","value"]:["tag","enabled"],ctx);empty(c,ctx);const ot=literal(a.tag,"tag",ctx,c);if(name==="Axis")result.axes.push({tag:ot,value:parseNumber(literal(a.value,"value",ctx,c))});else {const enabled=literal(a.enabled,"enabled",ctx,c);if(!["true","false"].includes(enabled))return ctx.fail("TYPO_FEATURE","enabled must be true or false",c.span);result.features.push({tag:ot,enabled:enabled==="true"});}continue;}
 const specs:Record<string,string[]>={Fill:["color"],Stroke:["color","width","placement"],Shadow:["color","x","y","blur","spread"],Glow:["color","blur","spread"],Box:["color","target","continuity","padding","radius","border-width","border-color","border-style"],Decoration:["color","line","style","thickness","offset","skip-ink"]};if(!specs[name])return ctx.fail("MARKUP_CHILD",`Unknown typography paint ${name}`,c.span);const a=attributes(c,specs[name]!,ctx);const i=decodeInk(c,a);const num=(n:string,f?:string)=>parseNumber(literal(a[n],n,ctx,c,f));const text=(n:string,f?:string)=>literal(a[n],n,ctx,c,f);let paint:unknown;
 if(name==="Decoration"){for(const child of children(c,ctx))if(!["Linear","Radial"].includes(tag(child)))return ctx.fail("MARKUP_CHILD","Decoration only accepts a gradient",child.span);const skip=text("skip-ink","true");if(skip!=="true"&&skip!=="false")return ctx.fail("TYPO_PAINT","skip-ink must be true or false",c.span);const d={line:text("line"),ink:i,style:text("style","solid"),...(a.thickness?{thicknessPx:num("thickness")}:{}),...(a.offset?{offsetPx:num("offset")}:{}),skipInk:skip==="true"};result.decorations.push(d as Decoration);continue;}
 if(name==="Fill")paint={kind:"fill",ink:i};else if(name==="Stroke")paint={kind:"stroke",ink:i,widthPx:num("width"),placement:text("placement")};else if(name==="Shadow")paint={kind:"shadow",ink:i,xPx:num("x"),yPx:num("y"),blurPx:num("blur"),spreadPx:num("spread","0")};else if(name==="Glow")paint={kind:"glow",ink:i,blurPx:num("blur"),spreadPx:num("spread","0")};else {const shadows=[];let tail:unknown;for(const child of children(c,ctx)){const childName=tag(child);if(["Linear","Radial"].includes(childName))continue;if(childName==="BoxShadow"){const ca=attributes(child,["color","x","y","blur","spread"],ctx);empty(child,ctx);shadows.push({color:literal(ca.color,"color",ctx,child),xPx:parseNumber(literal(ca.x,"x",ctx,child,"0")),yPx:parseNumber(literal(ca.y,"y",ctx,child,"0")),blurPx:parseNumber(literal(ca.blur,"blur",ctx,child,"0")),spreadPx:parseNumber(literal(ca.spread,"spread",ctx,child,"0"))});}else if(childName==="Tail"&&!tail){const ca=attributes(child,["side","offset","width","height","color"],ctx);empty(child,ctx);tail={side:literal(ca.side,"side",ctx,child),offsetPx:parseNumber(literal(ca.offset,"offset",ctx,child)),widthPx:parseNumber(literal(ca.width,"width",ctx,child)),heightPx:parseNumber(literal(ca.height,"height",ctx,child)),color:literal(ca.color,"color",ctx,child)};}else return ctx.fail("MARKUP_CHILD","Invalid box child",child.span);}if(!!a["border-color"]!==!!a["border-width"])return ctx.fail("TYPO_PAINT","Border needs color and width",c.span);paint={kind:"box",ink:i,target:text("target"),continuity:text("continuity","isolated"),paddingPx:sides(text("padding","0")),radiusPx:sides(text("radius","0")),shadows,...(a["border-color"]?{border:{ink:{kind:"solid",color:text("border-color")},widthPx:sides(text("border-width")),style:text("border-style","solid")}}:{}),...(tail?{tail}:{})};}
 for(const child of children(c,ctx))if(!["Linear","Radial",...(name==="Box"?["BoxShadow","Tail"]:[])].includes(tag(child)))return ctx.fail("MARKUP_CHILD","Unexpected paint child",child.span);validatePaint(paint);result.paints.push(paint);
 }
 return result;
}
const motionAttrs=["at","easing","x","y","scale","rotate","skew-x","skew-y","opacity","blur","clip-top","clip-right","clip-bottom","clip-left","color"];
export function decodeMotion(e:ElementNode|RawElement,ctx:ElaborationContext,motionKey:string):TypographyMotion {
 const motion:TypographyMotion={motionKey,itemKeys:[],pathKeys:[],sequences:[]};
 const pose=(c:ElementNode)=>{const a=attributes(c,motionAttrs,ctx);empty(c,ctx);const n=(name:string,f:string)=>parseNumber(literal(a[name],name,ctx,c,f));const declarations:{property:AnimatedProperty|"color";value:string}[]=[];
 if(a.opacity&&(n("opacity","1")<0||n("opacity","1")>1)||a.blur&&n("blur","0")<0||["clip-top","clip-right","clip-bottom","clip-left"].some(name=>a[name]&&n(name,"0")<0))return ctx.fail("TYPO_MOTION","Opacity must be in [0,1]; blur and clip insets must be nonnegative",c.span);
 if(["x","y","scale","rotate","skew-x","skew-y"].some(n=>a[n]))declarations.push({property:"transform",value:`translate(${n("x","0")}px,${n("y","0")}px) scale(${n("scale","1")}) rotate(${n("rotate","0")}deg) skew(${n("skew-x","0")}deg,${n("skew-y","0")}deg)`});if(a.opacity)declarations.push({property:"opacity",value:String(n("opacity","1"))});if(a.blur)declarations.push({property:"filter",value:`blur(${n("blur","0")}px)`});if(["clip-top","clip-right","clip-bottom","clip-left"].some(n=>a[n]))declarations.push({property:"clip-path",value:`inset(${["clip-top","clip-right","clip-bottom","clip-left"].map(name=>n(name,"0")+"px").join(" ")})`});if(a.color)declarations.push({property:"color",value:literal(a.color,"color",ctx,c)});if(!declarations.length)return ctx.fail("TYPO_MOTION","Keyframe needs animated properties",c.span);return{at:parseNumber(literal(a.at,"at",ctx,c)),easing:literal(a.easing,"easing",ctx,c,"linear") as Easing,declarations};};
 for(const c of children(e,ctx)){const name=c.tag.split(":").at(-1);if(name==="ItemKeyframe"){const p=pose(c);motion.itemKeys.push({offsetFrames:p.at,easing:p.easing,declarations:p.declarations});}else if(name==="PathKeyframe"){const a=attributes(c,["at","margin","easing"],ctx);empty(c,ctx);motion.pathKeys.push({offsetFrames:parseNumber(literal(a.at,"at",ctx,c)),marginPx:parseNumber(literal(a.margin,"margin",ctx,c)),easing:literal(a.easing,"easing",ctx,c,"linear") as Easing});}else if(name==="Sequence"){const a=attributes(c,["id","unit","start-index","end-index","duration-frames","order","start-frame","stagger-frames","cycles","seed"],ctx);const t=(n:string,f?:string)=>literal(a[n],n,ctx,c,f);const n=(name:string,f?:string)=>parseNumber(t(name,f));const poses=children(c,ctx).map(k=>{if(k.tag.split(":").at(-1)!=="Keyframe")return ctx.fail("MARKUP_CHILD","Sequence only accepts Keyframe",k.span);const p=pose(k);return{progress:p.at,easing:p.easing,declarations:p.declarations};});motion.sequences.push({sequenceKey:motionKey+"/"+t("id"),unit:t("unit") as TypographyMotion["sequences"][number]["unit"],units:{start:n("start-index"),end:n("end-index")},startFrame:n("start-frame","0"),durationFrames:n("duration-frames"),staggerFrames:n("stagger-frames","0"),cycles:n("cycles","1"),order:t("order","forward") as "forward"|"reverse"|"random",...(a.seed?{seed:n("seed")}:{}),poses});}else return ctx.fail("MARKUP_CHILD","Motion only accepts ItemKeyframe, PathKeyframe and Sequence",c.span);}
 return motion;
}
